#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="livegame")]
	public partial class livegameDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertJugadores(Jugadores instance);
    partial void UpdateJugadores(Jugadores instance);
    partial void DeleteJugadores(Jugadores instance);
    partial void InsertEquipo(Equipo instance);
    partial void UpdateEquipo(Equipo instance);
    partial void DeleteEquipo(Equipo instance);
    partial void InsertEstadistica(Estadistica instance);
    partial void UpdateEstadistica(Estadistica instance);
    partial void DeleteEstadistica(Estadistica instance);
    partial void InsertCalendario(Calendario instance);
    partial void UpdateCalendario(Calendario instance);
    partial void DeleteCalendario(Calendario instance);
    #endregion
		
		public livegameDataContext() : 
				base(global::Repositorio.Properties.Settings.Default.livegameConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public livegameDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public livegameDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public livegameDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public livegameDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Usuario> Usuarios
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<Jugadores> Jugadores
		{
			get
			{
				return this.GetTable<Jugadores>();
			}
		}
		
		public System.Data.Linq.Table<Equipo> Equipos
		{
			get
			{
				return this.GetTable<Equipo>();
			}
		}
		
		public System.Data.Linq.Table<Estadistica> Estadisticas
		{
			get
			{
				return this.GetTable<Estadistica>();
			}
		}
		
		public System.Data.Linq.Table<Narracione> Narraciones
		{
			get
			{
				return this.GetTable<Narracione>();
			}
		}
		
		public System.Data.Linq.Table<Calendario> Calendarios
		{
			get
			{
				return this.GetTable<Calendario>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _nombre_usuario;
		
		private System.Nullable<int> _id;
		
		private string _tipo;
		
		private string _contraseña;
		
		private string _correo;
		
		private string _nombre;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onnombre_usuarioChanging(string value);
    partial void Onnombre_usuarioChanged();
    partial void OnidChanging(System.Nullable<int> value);
    partial void OnidChanged();
    partial void OntipoChanging(string value);
    partial void OntipoChanged();
    partial void OncontraseñaChanging(string value);
    partial void OncontraseñaChanged();
    partial void OncorreoChanging(string value);
    partial void OncorreoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    #endregion
		
		public Usuario()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre_usuario", DbType="VarChar(25) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string nombre_usuario
		{
			get
			{
				return this._nombre_usuario;
			}
			set
			{
				if ((this._nombre_usuario != value))
				{
					this.Onnombre_usuarioChanging(value);
					this.SendPropertyChanging();
					this._nombre_usuario = value;
					this.SendPropertyChanged("nombre_usuario");
					this.Onnombre_usuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int")]
		public System.Nullable<int> id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo", DbType="VarChar(10)")]
		public string tipo
		{
			get
			{
				return this._tipo;
			}
			set
			{
				if ((this._tipo != value))
				{
					this.OntipoChanging(value);
					this.SendPropertyChanging();
					this._tipo = value;
					this.SendPropertyChanged("tipo");
					this.OntipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contraseña", DbType="VarChar(25)")]
		public string contraseña
		{
			get
			{
				return this._contraseña;
			}
			set
			{
				if ((this._contraseña != value))
				{
					this.OncontraseñaChanging(value);
					this.SendPropertyChanging();
					this._contraseña = value;
					this.SendPropertyChanged("contraseña");
					this.OncontraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_correo", DbType="VarChar(50)")]
		public string correo
		{
			get
			{
				return this._correo;
			}
			set
			{
				if ((this._correo != value))
				{
					this.OncorreoChanging(value);
					this.SendPropertyChanging();
					this._correo = value;
					this.SendPropertyChanged("correo");
					this.OncorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(30)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Jugadores")]
	public partial class Jugadores : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _id;
		
		private string _nombre;
		
		private System.Nullable<int> _dorsal;
		
		private string _equipo;
		
		private string _pos;
		
		private System.Nullable<int> _edad;
		
		private System.Nullable<int> _salario;
		
		private string _twitter;
		
		private System.Nullable<decimal> _tfollows;
		
		private string _activo;
		
		private EntitySet<Estadistica> _Estadisticas;
		
		private EntityRef<Equipo> _Equipo1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(System.Nullable<int> value);
    partial void OnidChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OndorsalChanging(System.Nullable<int> value);
    partial void OndorsalChanged();
    partial void OnequipoChanging(string value);
    partial void OnequipoChanged();
    partial void OnposChanging(string value);
    partial void OnposChanged();
    partial void OnedadChanging(System.Nullable<int> value);
    partial void OnedadChanged();
    partial void OnsalarioChanging(System.Nullable<int> value);
    partial void OnsalarioChanged();
    partial void OntwitterChanging(string value);
    partial void OntwitterChanged();
    partial void OntfollowsChanging(System.Nullable<decimal> value);
    partial void OntfollowsChanged();
    partial void OnactivoChanging(string value);
    partial void OnactivoChanged();
    #endregion
		
		public Jugadores()
		{
			this._Estadisticas = new EntitySet<Estadistica>(new Action<Estadistica>(this.attach_Estadisticas), new Action<Estadistica>(this.detach_Estadisticas));
			this._Equipo1 = default(EntityRef<Equipo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int")]
		public System.Nullable<int> id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(24) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dorsal", DbType="Int")]
		public System.Nullable<int> dorsal
		{
			get
			{
				return this._dorsal;
			}
			set
			{
				if ((this._dorsal != value))
				{
					this.OndorsalChanging(value);
					this.SendPropertyChanging();
					this._dorsal = value;
					this.SendPropertyChanged("dorsal");
					this.OndorsalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_equipo", DbType="VarChar(9)")]
		public string equipo
		{
			get
			{
				return this._equipo;
			}
			set
			{
				if ((this._equipo != value))
				{
					if (this._Equipo1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnequipoChanging(value);
					this.SendPropertyChanging();
					this._equipo = value;
					this.SendPropertyChanged("equipo");
					this.OnequipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pos", DbType="VarChar(3)")]
		public string pos
		{
			get
			{
				return this._pos;
			}
			set
			{
				if ((this._pos != value))
				{
					this.OnposChanging(value);
					this.SendPropertyChanging();
					this._pos = value;
					this.SendPropertyChanged("pos");
					this.OnposChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_edad", DbType="Int")]
		public System.Nullable<int> edad
		{
			get
			{
				return this._edad;
			}
			set
			{
				if ((this._edad != value))
				{
					this.OnedadChanging(value);
					this.SendPropertyChanging();
					this._edad = value;
					this.SendPropertyChanged("edad");
					this.OnedadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salario", DbType="Int")]
		public System.Nullable<int> salario
		{
			get
			{
				return this._salario;
			}
			set
			{
				if ((this._salario != value))
				{
					this.OnsalarioChanging(value);
					this.SendPropertyChanging();
					this._salario = value;
					this.SendPropertyChanged("salario");
					this.OnsalarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_twitter", DbType="VarChar(15)")]
		public string twitter
		{
			get
			{
				return this._twitter;
			}
			set
			{
				if ((this._twitter != value))
				{
					this.OntwitterChanging(value);
					this.SendPropertyChanging();
					this._twitter = value;
					this.SendPropertyChanged("twitter");
					this.OntwitterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tfollows", DbType="Decimal(11,3)")]
		public System.Nullable<decimal> tfollows
		{
			get
			{
				return this._tfollows;
			}
			set
			{
				if ((this._tfollows != value))
				{
					this.OntfollowsChanging(value);
					this.SendPropertyChanging();
					this._tfollows = value;
					this.SendPropertyChanged("tfollows");
					this.OntfollowsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activo", DbType="VarChar(4)")]
		public string activo
		{
			get
			{
				return this._activo;
			}
			set
			{
				if ((this._activo != value))
				{
					this.OnactivoChanging(value);
					this.SendPropertyChanging();
					this._activo = value;
					this.SendPropertyChanged("activo");
					this.OnactivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Jugadores_Estadistica", Storage="_Estadisticas", ThisKey="nombre", OtherKey="jugador")]
		public EntitySet<Estadistica> Estadisticas
		{
			get
			{
				return this._Estadisticas;
			}
			set
			{
				this._Estadisticas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Equipo_Jugadores", Storage="_Equipo1", ThisKey="equipo", OtherKey="ht", IsForeignKey=true)]
		public Equipo Equipo1
		{
			get
			{
				return this._Equipo1.Entity;
			}
			set
			{
				Equipo previousValue = this._Equipo1.Entity;
				if (((previousValue != value) 
							|| (this._Equipo1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Equipo1.Entity = null;
						previousValue.Jugadores.Remove(this);
					}
					this._Equipo1.Entity = value;
					if ((value != null))
					{
						value.Jugadores.Add(this);
						this._equipo = value.ht;
					}
					else
					{
						this._equipo = default(string);
					}
					this.SendPropertyChanged("Equipo1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Estadisticas(Estadistica entity)
		{
			this.SendPropertyChanging();
			entity.Jugadores = this;
		}
		
		private void detach_Estadisticas(Estadistica entity)
		{
			this.SendPropertyChanging();
			entity.Jugadores = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Equipos")]
	public partial class Equipo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ht;
		
		private string _nombre;
		
		private string _twitter;
		
		private string _ref;
		
		private System.Nullable<int> _followers;
		
		private string _conferencia;
		
		private string _estadio;
		
		private string _entrenador;
		
		private string _ubicacion;
		
		private System.Nullable<int> _fundacion;
		
		private string _activo;
		
		private System.Nullable<decimal> _GStars;
		
		private System.Nullable<decimal> _TWstars;
		
		private EntitySet<Jugadores> _Jugadores;
		
		private EntitySet<Estadistica> _Estadisticas;
		
		private EntitySet<Calendario> _Calendarios;
		
		private EntitySet<Calendario> _Calendarios1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnhtChanging(string value);
    partial void OnhtChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OntwitterChanging(string value);
    partial void OntwitterChanged();
    partial void OnrefChanging(string value);
    partial void OnrefChanged();
    partial void OnfollowersChanging(System.Nullable<int> value);
    partial void OnfollowersChanged();
    partial void OnconferenciaChanging(string value);
    partial void OnconferenciaChanged();
    partial void OnestadioChanging(string value);
    partial void OnestadioChanged();
    partial void OnentrenadorChanging(string value);
    partial void OnentrenadorChanged();
    partial void OnubicacionChanging(string value);
    partial void OnubicacionChanged();
    partial void OnfundacionChanging(System.Nullable<int> value);
    partial void OnfundacionChanged();
    partial void OnactivoChanging(string value);
    partial void OnactivoChanged();
    partial void OnGStarsChanging(System.Nullable<decimal> value);
    partial void OnGStarsChanged();
    partial void OnTWstarsChanging(System.Nullable<decimal> value);
    partial void OnTWstarsChanged();
    #endregion
		
		public Equipo()
		{
			this._Jugadores = new EntitySet<Jugadores>(new Action<Jugadores>(this.attach_Jugadores), new Action<Jugadores>(this.detach_Jugadores));
			this._Estadisticas = new EntitySet<Estadistica>(new Action<Estadistica>(this.attach_Estadisticas), new Action<Estadistica>(this.detach_Estadisticas));
			this._Calendarios = new EntitySet<Calendario>(new Action<Calendario>(this.attach_Calendarios), new Action<Calendario>(this.detach_Calendarios));
			this._Calendarios1 = new EntitySet<Calendario>(new Action<Calendario>(this.attach_Calendarios1), new Action<Calendario>(this.detach_Calendarios1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ht", DbType="VarChar(9) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ht
		{
			get
			{
				return this._ht;
			}
			set
			{
				if ((this._ht != value))
				{
					this.OnhtChanging(value);
					this.SendPropertyChanging();
					this._ht = value;
					this.SendPropertyChanged("ht");
					this.OnhtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(22)")]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_twitter", DbType="VarChar(15)")]
		public string twitter
		{
			get
			{
				return this._twitter;
			}
			set
			{
				if ((this._twitter != value))
				{
					this.OntwitterChanging(value);
					this.SendPropertyChanging();
					this._twitter = value;
					this.SendPropertyChanged("twitter");
					this.OntwitterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ref", Storage="_ref", DbType="VarChar(12)")]
		public string @ref
		{
			get
			{
				return this._ref;
			}
			set
			{
				if ((this._ref != value))
				{
					this.OnrefChanging(value);
					this.SendPropertyChanging();
					this._ref = value;
					this.SendPropertyChanged("@ref");
					this.OnrefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_followers", DbType="Int")]
		public System.Nullable<int> followers
		{
			get
			{
				return this._followers;
			}
			set
			{
				if ((this._followers != value))
				{
					this.OnfollowersChanging(value);
					this.SendPropertyChanging();
					this._followers = value;
					this.SendPropertyChanged("followers");
					this.OnfollowersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_conferencia", DbType="VarChar(5)")]
		public string conferencia
		{
			get
			{
				return this._conferencia;
			}
			set
			{
				if ((this._conferencia != value))
				{
					this.OnconferenciaChanging(value);
					this.SendPropertyChanging();
					this._conferencia = value;
					this.SendPropertyChanged("conferencia");
					this.OnconferenciaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estadio", DbType="VarChar(26)")]
		public string estadio
		{
			get
			{
				return this._estadio;
			}
			set
			{
				if ((this._estadio != value))
				{
					this.OnestadioChanging(value);
					this.SendPropertyChanging();
					this._estadio = value;
					this.SendPropertyChanged("estadio");
					this.OnestadioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_entrenador", DbType="VarChar(29)")]
		public string entrenador
		{
			get
			{
				return this._entrenador;
			}
			set
			{
				if ((this._entrenador != value))
				{
					this.OnentrenadorChanging(value);
					this.SendPropertyChanging();
					this._entrenador = value;
					this.SendPropertyChanged("entrenador");
					this.OnentrenadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ubicacion", DbType="VarChar(30)")]
		public string ubicacion
		{
			get
			{
				return this._ubicacion;
			}
			set
			{
				if ((this._ubicacion != value))
				{
					this.OnubicacionChanging(value);
					this.SendPropertyChanging();
					this._ubicacion = value;
					this.SendPropertyChanged("ubicacion");
					this.OnubicacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fundacion", DbType="Int")]
		public System.Nullable<int> fundacion
		{
			get
			{
				return this._fundacion;
			}
			set
			{
				if ((this._fundacion != value))
				{
					this.OnfundacionChanging(value);
					this.SendPropertyChanging();
					this._fundacion = value;
					this.SendPropertyChanged("fundacion");
					this.OnfundacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_activo", DbType="VarChar(4)")]
		public string activo
		{
			get
			{
				return this._activo;
			}
			set
			{
				if ((this._activo != value))
				{
					this.OnactivoChanging(value);
					this.SendPropertyChanging();
					this._activo = value;
					this.SendPropertyChanged("activo");
					this.OnactivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GStars", DbType="Decimal(3,1)")]
		public System.Nullable<decimal> GStars
		{
			get
			{
				return this._GStars;
			}
			set
			{
				if ((this._GStars != value))
				{
					this.OnGStarsChanging(value);
					this.SendPropertyChanging();
					this._GStars = value;
					this.SendPropertyChanged("GStars");
					this.OnGStarsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TWstars", DbType="Decimal(3,1)")]
		public System.Nullable<decimal> TWstars
		{
			get
			{
				return this._TWstars;
			}
			set
			{
				if ((this._TWstars != value))
				{
					this.OnTWstarsChanging(value);
					this.SendPropertyChanging();
					this._TWstars = value;
					this.SendPropertyChanged("TWstars");
					this.OnTWstarsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Equipo_Jugadores", Storage="_Jugadores", ThisKey="ht", OtherKey="equipo")]
		public EntitySet<Jugadores> Jugadores
		{
			get
			{
				return this._Jugadores;
			}
			set
			{
				this._Jugadores.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Equipo_Estadistica", Storage="_Estadisticas", ThisKey="ht", OtherKey="equipo")]
		public EntitySet<Estadistica> Estadisticas
		{
			get
			{
				return this._Estadisticas;
			}
			set
			{
				this._Estadisticas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Equipo_Calendario", Storage="_Calendarios", ThisKey="ht", OtherKey="local")]
		public EntitySet<Calendario> Calendarios
		{
			get
			{
				return this._Calendarios;
			}
			set
			{
				this._Calendarios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Equipo_Calendario1", Storage="_Calendarios1", ThisKey="ht", OtherKey="visita")]
		public EntitySet<Calendario> Calendarios1
		{
			get
			{
				return this._Calendarios1;
			}
			set
			{
				this._Calendarios1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Jugadores(Jugadores entity)
		{
			this.SendPropertyChanging();
			entity.Equipo1 = this;
		}
		
		private void detach_Jugadores(Jugadores entity)
		{
			this.SendPropertyChanging();
			entity.Equipo1 = null;
		}
		
		private void attach_Estadisticas(Estadistica entity)
		{
			this.SendPropertyChanging();
			entity.Equipo1 = this;
		}
		
		private void detach_Estadisticas(Estadistica entity)
		{
			this.SendPropertyChanging();
			entity.Equipo1 = null;
		}
		
		private void attach_Calendarios(Calendario entity)
		{
			this.SendPropertyChanging();
			entity.Equipo = this;
		}
		
		private void detach_Calendarios(Calendario entity)
		{
			this.SendPropertyChanging();
			entity.Equipo = null;
		}
		
		private void attach_Calendarios1(Calendario entity)
		{
			this.SendPropertyChanging();
			entity.Equipo1 = this;
		}
		
		private void detach_Calendarios1(Calendario entity)
		{
			this.SendPropertyChanging();
			entity.Equipo1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Estadisticas")]
	public partial class Estadistica : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _temporada;
		
		private string _equipo;
		
		private string _jugador;
		
		private System.Nullable<int> _partidas;
		
		private System.Nullable<int> _puntos;
		
		private System.Nullable<decimal> _rebotes;
		
		private System.Nullable<decimal> _pgoldecampo;
		
		private System.Nullable<decimal> _pgolcampo;
		
		private System.Nullable<decimal> _ptirolibre;
		
		private System.Nullable<decimal> _asistencias;
		
		private System.Nullable<decimal> _robos;
		
		private System.Nullable<decimal> _bloqueos;
		
		private EntityRef<Equipo> _Equipo1;
		
		private EntityRef<Jugadores> _Jugadores;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntemporadaChanging(string value);
    partial void OntemporadaChanged();
    partial void OnequipoChanging(string value);
    partial void OnequipoChanged();
    partial void OnjugadorChanging(string value);
    partial void OnjugadorChanged();
    partial void OnpartidasChanging(System.Nullable<int> value);
    partial void OnpartidasChanged();
    partial void OnpuntosChanging(System.Nullable<int> value);
    partial void OnpuntosChanged();
    partial void OnrebotesChanging(System.Nullable<decimal> value);
    partial void OnrebotesChanged();
    partial void OnpgoldecampoChanging(System.Nullable<decimal> value);
    partial void OnpgoldecampoChanged();
    partial void OnpgolcampoChanging(System.Nullable<decimal> value);
    partial void OnpgolcampoChanged();
    partial void OnptirolibreChanging(System.Nullable<decimal> value);
    partial void OnptirolibreChanged();
    partial void OnasistenciasChanging(System.Nullable<decimal> value);
    partial void OnasistenciasChanged();
    partial void OnrobosChanging(System.Nullable<decimal> value);
    partial void OnrobosChanged();
    partial void OnbloqueosChanging(System.Nullable<decimal> value);
    partial void OnbloqueosChanged();
    #endregion
		
		public Estadistica()
		{
			this._Equipo1 = default(EntityRef<Equipo>);
			this._Jugadores = default(EntityRef<Jugadores>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_temporada", DbType="VarChar(9)")]
		public string temporada
		{
			get
			{
				return this._temporada;
			}
			set
			{
				if ((this._temporada != value))
				{
					this.OntemporadaChanging(value);
					this.SendPropertyChanging();
					this._temporada = value;
					this.SendPropertyChanged("temporada");
					this.OntemporadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_equipo", DbType="VarChar(9)")]
		public string equipo
		{
			get
			{
				return this._equipo;
			}
			set
			{
				if ((this._equipo != value))
				{
					if (this._Equipo1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnequipoChanging(value);
					this.SendPropertyChanging();
					this._equipo = value;
					this.SendPropertyChanged("equipo");
					this.OnequipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jugador", DbType="VarChar(24)")]
		public string jugador
		{
			get
			{
				return this._jugador;
			}
			set
			{
				if ((this._jugador != value))
				{
					if (this._Jugadores.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnjugadorChanging(value);
					this.SendPropertyChanging();
					this._jugador = value;
					this.SendPropertyChanged("jugador");
					this.OnjugadorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_partidas", DbType="Int")]
		public System.Nullable<int> partidas
		{
			get
			{
				return this._partidas;
			}
			set
			{
				if ((this._partidas != value))
				{
					this.OnpartidasChanging(value);
					this.SendPropertyChanging();
					this._partidas = value;
					this.SendPropertyChanged("partidas");
					this.OnpartidasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puntos", DbType="Int")]
		public System.Nullable<int> puntos
		{
			get
			{
				return this._puntos;
			}
			set
			{
				if ((this._puntos != value))
				{
					this.OnpuntosChanging(value);
					this.SendPropertyChanging();
					this._puntos = value;
					this.SendPropertyChanged("puntos");
					this.OnpuntosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rebotes", DbType="Decimal(2,1)")]
		public System.Nullable<decimal> rebotes
		{
			get
			{
				return this._rebotes;
			}
			set
			{
				if ((this._rebotes != value))
				{
					this.OnrebotesChanging(value);
					this.SendPropertyChanging();
					this._rebotes = value;
					this.SendPropertyChanged("rebotes");
					this.OnrebotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pgoldecampo", DbType="Decimal(2,1)")]
		public System.Nullable<decimal> pgoldecampo
		{
			get
			{
				return this._pgoldecampo;
			}
			set
			{
				if ((this._pgoldecampo != value))
				{
					this.OnpgoldecampoChanging(value);
					this.SendPropertyChanging();
					this._pgoldecampo = value;
					this.SendPropertyChanged("pgoldecampo");
					this.OnpgoldecampoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pgolcampo", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> pgolcampo
		{
			get
			{
				return this._pgolcampo;
			}
			set
			{
				if ((this._pgolcampo != value))
				{
					this.OnpgolcampoChanging(value);
					this.SendPropertyChanging();
					this._pgolcampo = value;
					this.SendPropertyChanged("pgolcampo");
					this.OnpgolcampoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ptirolibre", DbType="Decimal(4,2)")]
		public System.Nullable<decimal> ptirolibre
		{
			get
			{
				return this._ptirolibre;
			}
			set
			{
				if ((this._ptirolibre != value))
				{
					this.OnptirolibreChanging(value);
					this.SendPropertyChanging();
					this._ptirolibre = value;
					this.SendPropertyChanged("ptirolibre");
					this.OnptirolibreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_asistencias", DbType="Decimal(2,1)")]
		public System.Nullable<decimal> asistencias
		{
			get
			{
				return this._asistencias;
			}
			set
			{
				if ((this._asistencias != value))
				{
					this.OnasistenciasChanging(value);
					this.SendPropertyChanging();
					this._asistencias = value;
					this.SendPropertyChanged("asistencias");
					this.OnasistenciasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_robos", DbType="Decimal(2,1)")]
		public System.Nullable<decimal> robos
		{
			get
			{
				return this._robos;
			}
			set
			{
				if ((this._robos != value))
				{
					this.OnrobosChanging(value);
					this.SendPropertyChanging();
					this._robos = value;
					this.SendPropertyChanged("robos");
					this.OnrobosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bloqueos", DbType="Decimal(2,1)")]
		public System.Nullable<decimal> bloqueos
		{
			get
			{
				return this._bloqueos;
			}
			set
			{
				if ((this._bloqueos != value))
				{
					this.OnbloqueosChanging(value);
					this.SendPropertyChanging();
					this._bloqueos = value;
					this.SendPropertyChanged("bloqueos");
					this.OnbloqueosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Equipo_Estadistica", Storage="_Equipo1", ThisKey="equipo", OtherKey="ht", IsForeignKey=true)]
		public Equipo Equipo1
		{
			get
			{
				return this._Equipo1.Entity;
			}
			set
			{
				Equipo previousValue = this._Equipo1.Entity;
				if (((previousValue != value) 
							|| (this._Equipo1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Equipo1.Entity = null;
						previousValue.Estadisticas.Remove(this);
					}
					this._Equipo1.Entity = value;
					if ((value != null))
					{
						value.Estadisticas.Add(this);
						this._equipo = value.ht;
					}
					else
					{
						this._equipo = default(string);
					}
					this.SendPropertyChanged("Equipo1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Jugadores_Estadistica", Storage="_Jugadores", ThisKey="jugador", OtherKey="nombre", IsForeignKey=true)]
		public Jugadores Jugadores
		{
			get
			{
				return this._Jugadores.Entity;
			}
			set
			{
				Jugadores previousValue = this._Jugadores.Entity;
				if (((previousValue != value) 
							|| (this._Jugadores.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Jugadores.Entity = null;
						previousValue.Estadisticas.Remove(this);
					}
					this._Jugadores.Entity = value;
					if ((value != null))
					{
						value.Estadisticas.Add(this);
						this._jugador = value.nombre;
					}
					else
					{
						this._jugador = default(string);
					}
					this.SendPropertyChanged("Jugadores");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Narraciones")]
	public partial class Narracione
	{
		
		private System.Nullable<int> _idJuego;
		
		private string _admin;
		
		private string _comment;
		
		private string _twitter;
		
		public Narracione()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idJuego", DbType="Int")]
		public System.Nullable<int> idJuego
		{
			get
			{
				return this._idJuego;
			}
			set
			{
				if ((this._idJuego != value))
				{
					this._idJuego = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin", DbType="VarChar(25)")]
		public string admin
		{
			get
			{
				return this._admin;
			}
			set
			{
				if ((this._admin != value))
				{
					this._admin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comment", DbType="VarChar(39)")]
		public string comment
		{
			get
			{
				return this._comment;
			}
			set
			{
				if ((this._comment != value))
				{
					this._comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_twitter", DbType="VarChar(6)")]
		public string twitter
		{
			get
			{
				return this._twitter;
			}
			set
			{
				if ((this._twitter != value))
				{
					this._twitter = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Calendario")]
	public partial class Calendario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _temporada;
		
		private System.Nullable<System.DateTime> _fecha;
		
		private string _local;
		
		private string _visita;
		
		private System.Nullable<int> _pts_local;
		
		private System.Nullable<int> _pts_visita;
		
		private System.Nullable<int> _W;
		
		private System.Nullable<int> _L;
		
		private string _finalizado;
		
		private EntityRef<Equipo> _Equipo;
		
		private EntityRef<Equipo> _Equipo1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntemporadaChanging(string value);
    partial void OntemporadaChanged();
    partial void OnfechaChanging(System.Nullable<System.DateTime> value);
    partial void OnfechaChanged();
    partial void OnlocalChanging(string value);
    partial void OnlocalChanged();
    partial void OnvisitaChanging(string value);
    partial void OnvisitaChanged();
    partial void Onpts_localChanging(System.Nullable<int> value);
    partial void Onpts_localChanged();
    partial void Onpts_visitaChanging(System.Nullable<int> value);
    partial void Onpts_visitaChanged();
    partial void OnWChanging(System.Nullable<int> value);
    partial void OnWChanged();
    partial void OnLChanging(System.Nullable<int> value);
    partial void OnLChanged();
    partial void OnfinalizadoChanging(string value);
    partial void OnfinalizadoChanged();
    #endregion
		
		public Calendario()
		{
			this._Equipo = default(EntityRef<Equipo>);
			this._Equipo1 = default(EntityRef<Equipo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_temporada", DbType="VarChar(9)")]
		public string temporada
		{
			get
			{
				return this._temporada;
			}
			set
			{
				if ((this._temporada != value))
				{
					this.OntemporadaChanging(value);
					this.SendPropertyChanging();
					this._temporada = value;
					this.SendPropertyChanged("temporada");
					this.OntemporadaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="DateTime")]
		public System.Nullable<System.DateTime> fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_local", DbType="VarChar(9)")]
		public string local
		{
			get
			{
				return this._local;
			}
			set
			{
				if ((this._local != value))
				{
					if (this._Equipo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnlocalChanging(value);
					this.SendPropertyChanging();
					this._local = value;
					this.SendPropertyChanged("local");
					this.OnlocalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_visita", DbType="VarChar(9)")]
		public string visita
		{
			get
			{
				return this._visita;
			}
			set
			{
				if ((this._visita != value))
				{
					if (this._Equipo1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnvisitaChanging(value);
					this.SendPropertyChanging();
					this._visita = value;
					this.SendPropertyChanged("visita");
					this.OnvisitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pts_local", DbType="Int")]
		public System.Nullable<int> pts_local
		{
			get
			{
				return this._pts_local;
			}
			set
			{
				if ((this._pts_local != value))
				{
					this.Onpts_localChanging(value);
					this.SendPropertyChanging();
					this._pts_local = value;
					this.SendPropertyChanged("pts_local");
					this.Onpts_localChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pts_visita", DbType="Int")]
		public System.Nullable<int> pts_visita
		{
			get
			{
				return this._pts_visita;
			}
			set
			{
				if ((this._pts_visita != value))
				{
					this.Onpts_visitaChanging(value);
					this.SendPropertyChanging();
					this._pts_visita = value;
					this.SendPropertyChanged("pts_visita");
					this.Onpts_visitaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_W", DbType="Int")]
		public System.Nullable<int> W
		{
			get
			{
				return this._W;
			}
			set
			{
				if ((this._W != value))
				{
					this.OnWChanging(value);
					this.SendPropertyChanging();
					this._W = value;
					this.SendPropertyChanged("W");
					this.OnWChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_L", DbType="Int")]
		public System.Nullable<int> L
		{
			get
			{
				return this._L;
			}
			set
			{
				if ((this._L != value))
				{
					this.OnLChanging(value);
					this.SendPropertyChanging();
					this._L = value;
					this.SendPropertyChanged("L");
					this.OnLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_finalizado", DbType="VarChar(5)")]
		public string finalizado
		{
			get
			{
				return this._finalizado;
			}
			set
			{
				if ((this._finalizado != value))
				{
					this.OnfinalizadoChanging(value);
					this.SendPropertyChanging();
					this._finalizado = value;
					this.SendPropertyChanged("finalizado");
					this.OnfinalizadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Equipo_Calendario", Storage="_Equipo", ThisKey="local", OtherKey="ht", IsForeignKey=true)]
		public Equipo Equipo
		{
			get
			{
				return this._Equipo.Entity;
			}
			set
			{
				Equipo previousValue = this._Equipo.Entity;
				if (((previousValue != value) 
							|| (this._Equipo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Equipo.Entity = null;
						previousValue.Calendarios.Remove(this);
					}
					this._Equipo.Entity = value;
					if ((value != null))
					{
						value.Calendarios.Add(this);
						this._local = value.ht;
					}
					else
					{
						this._local = default(string);
					}
					this.SendPropertyChanged("Equipo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Equipo_Calendario1", Storage="_Equipo1", ThisKey="visita", OtherKey="ht", IsForeignKey=true)]
		public Equipo Equipo1
		{
			get
			{
				return this._Equipo1.Entity;
			}
			set
			{
				Equipo previousValue = this._Equipo1.Entity;
				if (((previousValue != value) 
							|| (this._Equipo1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Equipo1.Entity = null;
						previousValue.Calendarios1.Remove(this);
					}
					this._Equipo1.Entity = value;
					if ((value != null))
					{
						value.Calendarios1.Add(this);
						this._visita = value.ht;
					}
					else
					{
						this._visita = default(string);
					}
					this.SendPropertyChanged("Equipo1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
